server:
  port: 8002

eureka:
  instance:
    instance-id: payment-8002
    prefer-ip-address: true
  client:
    # 表示将自己注册进EurekaServer默认为true
    register-with-eureka: true
    # 表示可以从Eureka抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7003/eureka/,http://eureka7003.com:7003/eureka/
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:33060/2022?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: cloud
    password: cloud

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhang.cloud.entities