server:
  port: 8088

eureka:
  client:
    # 表示不讲其注入Eureka作为微服务，它就是个客户端
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    instance-id: hystrix-order80
    prefer-ip-address: true
